name: thor_devkit_dart
description: Dart package to assist smooth development on VeChain for developers and hobbyists.
version: 1.0.0
repository: https://github.com/SayNode/thor-devkit.dart/tree/main/thor_devkit_dart

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  pointycastle: ^3.5.2
  web3dart: ^2.3.5
  bip39: ^1.0.6
  bip32: ^2.0.0
  base_x: ^2.0.0
  rlp: ^2.0.0
  convert: ^3.0.2


dev_dependencies:
  test: ^1.21.1


